image: docker
services:
  - docker:dind
stages:
  - deploy
step-deploy-prod:
  stage: deploy
  script:
    - docker build -t app/notifier-front .
    - docker run -d -p 81:81 --rm --name ntf_front app/notifier-front